// Discover.idl : Discover 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(Discover.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(05F64CD3-F249-4CF7-BCAB-F60701A5192F),
	version(1.0),
]
library DiscoverLib
{
	importlib("stdole2.tlb");
};

