// Communicate.idl : Communicate 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(Communicate.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(5977783F-E06C-4818-98BA-2279BF14E349),
	version(1.0),
]
library CommunicateLib
{
	importlib("stdole2.tlb");
};

